=== raft/raft.github.io/implementation.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raft.github.io/implementation.schema.json",
    "title": "Raft Implementation",
    "description": "This file contains the schema describing a single Raft implementation.",
    "type": "object",
    "properties": {
        "repoURL": {
            "description": "URL pointing to base GitHub repo.",
            "type": "string",
            "pattern": "^https://github.com/([^/]+)/([^/]+)(?<!.git)$",
            "format": "uri"
        },
        "directory": {
            "description": "Optional path within Git repo where the Raft implementation is located.",
            "type": "string",
            "pattern": "^[^/].*/$"
        },
        "name": {
            "description": "Implementation project name. If the project is referred to as 'Raft', disambiguate it.",
            "type": "string",
            "pattern": "^.+(?<!^[Rr][Aa][Ff][Tt])$"
        },
        "authors": {
            "description": "List of primary authors (people). Try to keep this short.",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "description": "Person's name (or alias).",
                        "type": "string"
                    },
                    "twitter": {
                        "description": "Author's public Twitter username (without the @).",
                        "type": "string",
                        "pattern": "^[A-Za-z0-9_]{1,15}$"
                    },
                    "github": {
                        "description": "Author's GitHub username.",
                        "type": "string",
                        "pattern": "^[A-Za-z0-9]([A-Za-z0-9-]{0,37}[A-Za-z0-9]?)$"
                    },
                    "homepage": {
                        "description": "Author's public home page.",
                        "type": "string",
                        "format": "uri"
                    },
                    "organization": {
                        "description": "The author's affiliation for the project, such as an employer.",
                        "type": "string"
                    }
                },
                "required": [
                    "name"
                ],
                "additionalProperties": false
            },
            "maxItems": 7
        },
        "language": {
            "description": "Primary programming language for the implementation.",
            "type": "string"
        },
        "license": {
            "description": "SPDX license expression describing how the implementation may be used. See https://choosealicense.com/ or https://spdx.org/licenses/.",
            "type": "string"
        },
        "features": {
            "description": "Describe how complete the implementation is.",
            "type": "object",
            "properties": {
                "basic": {
                    "description": "The implementation handles leader election and log replication.",
                    "type": "boolean"
                },
                "persistence": {
                    "description": "The implementation safely persists the term and log to disk.",
                    "type": "boolean"
                },
                "logCompaction": {
                    "description": "The implementation does some form of log compaction, such as snapshotting.",
                    "type": "boolean"
                },
                "membershipChanges": {
                    "description": "The implementation can dynamically change the set of servers safely.",
                    "type": "boolean"
                }
            },
            "additionalProperties": false
        }
    },
    "required": [
        "name",
        "repoURL",
        "language"
    ],
    "additionalProperties": false
}

=== raft/raft.github.io/implementations.json
[
    {
        "repoURL": "https://github.com/42dot/foros",
        "name": "foros",
        "authors": [
            {
                "name": "Wonguk Jeong",
                "github": "huchijwk"
            }
        ],
        "language": "C++",
        "license": "Apache-2.0",
        "features": {
            "basic": true,
            "membershipChanges": false,
            "logCompaction": false,
            "persistence": true
        }
    },
    {
        "repoURL": "https://github.com/AChepurnoi/raft-kotlin",
        "name": "raft-kotlin",
        "authors": [
            {
                "name": "Sasha Chepurnoi",
                "github": "AChepurnoi"
            }
        ],
        "language": "Kotlin",
        "license": "MIT",
        "features": {
            "basic": true,
            "membershipChanges": true,
            "logCompaction": false
        }
    },
    {
        "repoURL": "https://github.com/EddieJ03/go-raft",
        "name": "goraft",
        "authors": [
            {
                "name": "Edward Jin, Henry Lin, Dhylan Patel",
                "github": "EddieJ03"
            }
        ],
        "language": "Go",
        "license": "MIT",
        "features": {
            "basic": true,
            "membershipChanges": false,
            "logCompaction": true,
            "persistence": true
        }
    },
    {
        "repoURL": "https://github.com/EdoardoV97/Raft-Omnet",
        "name": "Raft-Omnet",
        "authors": [
            {
                "name": "Edoardo Venir",
                "github": "EdoardoV97"
            },
            {
                "name": "Leonardo Ruzza",
                "github": "LeonardoRuzza"
            }
        ],
        "language": "Omnet++",
        "license": "Apache-2.0",
        "features": {
            "basic": true,
            "persistence": true,
            "membershipChanges": true,
            "logCompaction": true
        }
    },
    {
        "repoURL": "https://github.com/EmanueleGallone/RaftUDP",
        "name": "RaftUDP",
        "authors": [
            {
                "name": "Emanuele Gallone",
                "github": "EmanueleGallone"
            }
        ],
        "language": "Python",
        "license": "MIT",
        "features": {
            "basic": true,
            "membershipChanges": false,
            "logCompaction": false
        }
    },
    {
        "repoURL": "https://github.com/Hoverbear/raft",
        "name": "hoverbear/raft",
        "authors": [
            {
                "name": "Andrew Hobden",
                "twitter": "andrewhobden"
            },
            {
                "name": "Dan Burkert"
            }
        ],
        "language": "Rust",
        "license": "MIT",
        "features": {
            "basic": true,
            "membershipChanges": false,
            "logCompaction": false
        }
    },
    {
        "repoURL": "https://github.com/IvanProdaiko94/raft-protocol-implementation",
        "name": "IvanProdaiko94/raft-protocol-implementation",
        "authors": [
            {
                "name": "Ivan Prodaiko",
                "github": "IvanProdaiko94"
            }
        ],
        "language": "Go",
        "license": "MIT",
        "features": {
            "basic": true,
            "membershipChanges": false,
            "logCompaction": false
        }
    },
    {
        "repoURL": "https://github.com/LENSHOOD/go-raft",
        "name": "LENSHOOD/go-raft",
        "authors": [
            {
                "name": "Zhang Xuhai",
                "github": "LENSHOOD"
            }
        ],
        "language": "Go",
        "license": "MIT",
        "features": {
            "basic": true,
            "membershipChanges": false,
            "logCompaction": false,
            "persistence": false
        }
    },
    {
        "repoURL": "https://github.com/LVala/zaft",
        "name": "zaft",
        "authors": [
            {
                "name": "Lukasz Wala",
                "github": "LVala"
            }
        ],
        "language": "Zig",
        "license": "MIT",
        "features": {
            "basic": true,
            "membershipChanges": false,
            "logCompaction": false,
            "persistence": true
        }
    },
    {
        "repoURL": "https://github.com/LiangrunDa/raft-lite",
        "name": "Raft Lite",
        "authors": [
            {
                "name": "Liangrun Da",
                "github": "LiangrunDa"
            }
        ],
        "language": "Rust",
        "license": "MIT",
        "features": {
            "basic": true,
            "membershipChanges": false,
            "logCompaction": false,
            "persistence": true
        }
    },
    {
        "repoURL": "https://github.com/MicroRaft/MicroRaft",
        "name": "MicroRaft",
        "authors": [
            {
                "name": "Ensar Basri Kahveci",
                "github": "metanet"
            }
        ],
        "language": "Java",
        "license": "Apache-2.0",
        "features": {
            "basic": true,
            "membershipChanges": true,
            "logCompaction": true,
            "persistence": true
        }
    },
    {
        "repoURL": "https://github.com/NicolasT/kontiki",
        "name": "kontiki",
        "authors": [
            {
                "name": "Nicolas Trangez",
                "twitter": "eikke"
            }
        ],
        "language": "Haskell",
        "license": "BSD",
        "features": {
            "basic": false,
            "membershipChanges": false,
            "logCompaction": false
        }
    },
    {
        "repoURL": "https://github.com/Oaklight/Vesper",
        "name": "Vesper",
        "authors": [
            {
                "name": "Nicola Manzini",
                "github": "nmanzini"
            },
            {
                "name": "Peng Ding",
                "github": "Oaklight"
            }
        ],
        "language": "Python",
        "license": "MIT",
        "features": {
            "basic": true,
            "membershipChanges": true,
            "logCompaction": false
        }
    },
    {
        "repoURL": "https://github.com/Qihoo360/floyd",
        "name": "Qihoo360/raft",
        "authors": [
            {
                "name": "ZongzhiChen",
                "github": "baotiao"
            },
            {
                "name": "AnAnZhao",
                "github": "flabby"
            },
            {
                "name": "KangWang",
                "github": "CatKang"
            }
        ],
        "language": "C++",
        "license": "GPL-3.0",
        "features": {
            "basic": true,
            "membershipChanges": false,
            "logCompaction": false
        }
    },
    {
        "repoURL": "https://github.com/RedisLabs/redisraft",
        "name": "RedisRaft",
        "authors": [
            {
                "name": "Redis Labs",
                "github": "RedisLabs"
            }
        ],
        "language": "C",
        "license": "(AGPL-3.0 OR RSAL)",
        "features": {
            "basic": true,
            "membershipChanges": true,
            "logCompaction": true,
            "persistence": true
        }
    },
    {
        "repoURL": "https://github.com/TEAM-paxos/RaftChat",
        "name": "RaftChat",
        "authors": [
            {
                "name": "SoonWon Moon",
                "github": "damhiya"
            },
            {
                "name": "Bumsung Baek",
                "github": "highcloud100"
            }
        ],
        "language": "Rust",
        "license": "MIT",
        "features": {
            "basic": true,
            "membershipChanges": false,
            "logCompaction": false,
            "persistence": false
        }
    },
    {
        "repoURL": "https://github.com/Waqee/Raft-php",
        "name": "Raft-php",
        "authors": [
            {
                "name": "Waqee Khalid",
                "twitter": "WaqeeKhalid"
            }
        ],
        "language": "PHP",
        "license": "MIT",
        "features": {
            "basic": true,
            "membershipChanges": false,
            "logCompaction": false
        }
    },
    {
        "repoURL": "https://github.com/WhatsApp/waraft",
        "name": "waraft",
        "authors": [
            {
                "name": "WhatsApp",
                "github": "whatsapp"
            }
        ],
        "language": "Erlang",
        "license": "Apache-2.0",
        "features": {
            "basic": true,
            "membershipChanges": true,
            "logCompaction": true,
            "persistence": true
        }
    },
    {
        "repoURL": "https://github.com/aaronp/riff",
        "name": "Riff",
        "authors": [
            {
                "name": "Aaron Pritzlaff",
                "github": "aaronp"
            }
        ],
        "language": "Scala",
        "license": "Apache-2.0",
        "features": {
            "basic": true,
            "membershipChanges": true,
            "logCompaction": true,
            "persistence": true
        }
    },
    {
        "repoURL": "https://github.com/adsharma/raft",
        "name": "python3-raft",
        "authors": [
            {
                "name": "Arun Sharma",
                "github": "adsharma"
            },
            {
                "name": "Sean Reed"
            }
        ],
        "language": "Python",
        "license": "MIT",
        "features": {
            "basic": false,
            "membershipChanges": true,
            "logCompaction": false,
            "persistence": true
        }
    },
    {
        "repoURL": "https://github.com/akiradeveloper/lol",
        "name": "akiradeveloper/lol",
        "authors": [
            {
                "name": "Akira Hayakawa",
                "github": "akiradeveloper"
            }
        ],
        "language": "Rust",
